const TYPES = {
  ADD_PARTICLES: 16,
  EDIT_DISTANCE: 17,
  SET_H: 19,
  ROTATE_CAMERA_X: 20,
  SET_S: 23,
  ROTATE_PARTICLES_X: 24,
  SET_L: 27,
  ROTATE_PARTICLES_Z: 28,
  ROTATE_PARTICLES_Y: 46,
  ROTATE_CAMERA_Y: 50,
  ROTATE_CAMERA_Z: 54,
  AUTOROTATION: 1,
  RANDOM_COLORS: 3,
};
export default TYPES;
